import { AdvancedRuleDto } from "@/api/models/AdvancedRuleDto";

export const ADV_FIELD_OPTIONS = [
  { label: "用户ID", value: "userId", type: "text" as const },
  { label: "类型", value: "type", type: "text" as const },
  { label: "原因", value: "reason", type: "text" as const },
  { label: "说明", value: "detailReason", type: "text" as const },
  { label: "时长(天)", value: "durationDays", type: "text" as const },
  { label: "开始时间", value: "startsAt", type: "date" as const },
  { label: "过期时间", value: "expiresAt", type: "date" as const },
  { label: "处理人ID", value: "handlerId", type: "text" as const },
  { label: "是否撤销", value: "revoked", type: "bool" as const },
  { label: "撤销原因", value: "revokeReason", type: "text" as const },
  { label: "撤销说明", value: "revokeDetailReason", type: "text" as const },
  { label: "来源处罚ID", value: "sourcePunishmentId", type: "text" as const },
  { label: "创建时间", value: "createdAt", type: "date" as const },
];

export const OPS_BY_FIELD: Record<
  string,
  { label: string; value: AdvancedRuleDto.op }[]
> = {
  userId: [
    { label: "包含", value: AdvancedRuleDto.op.LIKE },
    { label: "等于", value: AdvancedRuleDto.op.EQUAL },
    { label: "不等于", value: AdvancedRuleDto.op.NOT_EQUAL },
    { label: "前缀匹配", value: AdvancedRuleDto.op.LIKE_RIGHT },
    { label: "后缀匹配", value: AdvancedRuleDto.op.LIKE_LEFT },
    { label: "为空", value: AdvancedRuleDto.op.IS_NULL },
    { label: "非空", value: AdvancedRuleDto.op.IS_NOT_NULL },
  ],
  type: [
    { label: "包含", value: AdvancedRuleDto.op.LIKE },
    { label: "等于", value: AdvancedRuleDto.op.EQUAL },
    { label: "不等于", value: AdvancedRuleDto.op.NOT_EQUAL },
    { label: "前缀匹配", value: AdvancedRuleDto.op.LIKE_RIGHT },
    { label: "后缀匹配", value: AdvancedRuleDto.op.LIKE_LEFT },
    { label: "为空", value: AdvancedRuleDto.op.IS_NULL },
    { label: "非空", value: AdvancedRuleDto.op.IS_NOT_NULL },
  ],
  reason: [
    { label: "包含", value: AdvancedRuleDto.op.LIKE },
    { label: "等于", value: AdvancedRuleDto.op.EQUAL },
    { label: "不等于", value: AdvancedRuleDto.op.NOT_EQUAL },
    { label: "前缀匹配", value: AdvancedRuleDto.op.LIKE_RIGHT },
    { label: "后缀匹配", value: AdvancedRuleDto.op.LIKE_LEFT },
    { label: "为空", value: AdvancedRuleDto.op.IS_NULL },
    { label: "非空", value: AdvancedRuleDto.op.IS_NOT_NULL },
  ],
  detailReason: [
    { label: "包含", value: AdvancedRuleDto.op.LIKE },
    { label: "等于", value: AdvancedRuleDto.op.EQUAL },
    { label: "不等于", value: AdvancedRuleDto.op.NOT_EQUAL },
    { label: "前缀匹配", value: AdvancedRuleDto.op.LIKE_RIGHT },
    { label: "后缀匹配", value: AdvancedRuleDto.op.LIKE_LEFT },
    { label: "为空", value: AdvancedRuleDto.op.IS_NULL },
    { label: "非空", value: AdvancedRuleDto.op.IS_NOT_NULL },
  ],
  durationDays: [
    { label: "等于", value: AdvancedRuleDto.op.EQUAL },
    { label: "不等于", value: AdvancedRuleDto.op.NOT_EQUAL },
    { label: "大于", value: AdvancedRuleDto.op.GREATER_THAN },
    { label: "大于等于", value: AdvancedRuleDto.op.GREATER_THAN_OR_EQUAL },
    { label: "小于", value: AdvancedRuleDto.op.LESS_THAN },
    { label: "小于等于", value: AdvancedRuleDto.op.LESS_THAN_OR_EQUAL },
    { label: "为空", value: AdvancedRuleDto.op.IS_NULL },
    { label: "非空", value: AdvancedRuleDto.op.IS_NOT_NULL },
  ],
  startsAt: [
    { label: "范围", value: AdvancedRuleDto.op.BETWEEN },
    { label: "大于", value: AdvancedRuleDto.op.GREATER_THAN },
    { label: "大于等于", value: AdvancedRuleDto.op.GREATER_THAN_OR_EQUAL },
    { label: "小于", value: AdvancedRuleDto.op.LESS_THAN },
    { label: "小于等于", value: AdvancedRuleDto.op.LESS_THAN_OR_EQUAL },
    { label: "为空", value: AdvancedRuleDto.op.IS_NULL },
    { label: "非空", value: AdvancedRuleDto.op.IS_NOT_NULL },
  ],
  expiresAt: [
    { label: "范围", value: AdvancedRuleDto.op.BETWEEN },
    { label: "大于", value: AdvancedRuleDto.op.GREATER_THAN },
    { label: "大于等于", value: AdvancedRuleDto.op.GREATER_THAN_OR_EQUAL },
    { label: "小于", value: AdvancedRuleDto.op.LESS_THAN },
    { label: "小于等于", value: AdvancedRuleDto.op.LESS_THAN_OR_EQUAL },
    { label: "为空", value: AdvancedRuleDto.op.IS_NULL },
    { label: "非空", value: AdvancedRuleDto.op.IS_NOT_NULL },
  ],
  handlerId: [
    { label: "包含", value: AdvancedRuleDto.op.LIKE },
    { label: "等于", value: AdvancedRuleDto.op.EQUAL },
    { label: "不等于", value: AdvancedRuleDto.op.NOT_EQUAL },
    { label: "前缀匹配", value: AdvancedRuleDto.op.LIKE_RIGHT },
    { label: "后缀匹配", value: AdvancedRuleDto.op.LIKE_LEFT },
    { label: "为空", value: AdvancedRuleDto.op.IS_NULL },
    { label: "非空", value: AdvancedRuleDto.op.IS_NOT_NULL },
  ],
  revoked: [{ label: "等于", value: AdvancedRuleDto.op.EQUAL }],
  revokeReason: [
    { label: "包含", value: AdvancedRuleDto.op.LIKE },
    { label: "等于", value: AdvancedRuleDto.op.EQUAL },
    { label: "不等于", value: AdvancedRuleDto.op.NOT_EQUAL },
    { label: "前缀匹配", value: AdvancedRuleDto.op.LIKE_RIGHT },
    { label: "后缀匹配", value: AdvancedRuleDto.op.LIKE_LEFT },
    { label: "为空", value: AdvancedRuleDto.op.IS_NULL },
    { label: "非空", value: AdvancedRuleDto.op.IS_NOT_NULL },
  ],
  revokeDetailReason: [
    { label: "包含", value: AdvancedRuleDto.op.LIKE },
    { label: "等于", value: AdvancedRuleDto.op.EQUAL },
    { label: "不等于", value: AdvancedRuleDto.op.NOT_EQUAL },
    { label: "前缀匹配", value: AdvancedRuleDto.op.LIKE_RIGHT },
    { label: "后缀匹配", value: AdvancedRuleDto.op.LIKE_LEFT },
    { label: "为空", value: AdvancedRuleDto.op.IS_NULL },
    { label: "非空", value: AdvancedRuleDto.op.IS_NOT_NULL },
  ],
  sourcePunishmentId: [
    { label: "包含", value: AdvancedRuleDto.op.LIKE },
    { label: "等于", value: AdvancedRuleDto.op.EQUAL },
    { label: "不等于", value: AdvancedRuleDto.op.NOT_EQUAL },
    { label: "前缀匹配", value: AdvancedRuleDto.op.LIKE_RIGHT },
    { label: "后缀匹配", value: AdvancedRuleDto.op.LIKE_LEFT },
    { label: "为空", value: AdvancedRuleDto.op.IS_NULL },
    { label: "非空", value: AdvancedRuleDto.op.IS_NOT_NULL },
  ],
  createdAt: [
    { label: "范围", value: AdvancedRuleDto.op.BETWEEN },
    { label: "大于", value: AdvancedRuleDto.op.GREATER_THAN },
    { label: "大于等于", value: AdvancedRuleDto.op.GREATER_THAN_OR_EQUAL },
    { label: "小于", value: AdvancedRuleDto.op.LESS_THAN },
    { label: "小于等于", value: AdvancedRuleDto.op.LESS_THAN_OR_EQUAL },
    { label: "为空", value: AdvancedRuleDto.op.IS_NULL },
    { label: "非空", value: AdvancedRuleDto.op.IS_NOT_NULL },
  ],
};
