/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AddFilmTorrentDto } from './models/AddFilmTorrentDto';
export type { AddSeriesFilmDto } from './models/AddSeriesFilmDto';
export type { AddThankDto } from './models/AddThankDto';
export type { AddThreadPromotionDto } from './models/AddThreadPromotionDto';
export type { AddThreadStickyDto } from './models/AddThreadStickyDto';
export type { AddTorrentPromotionDto } from './models/AddTorrentPromotionDto';
export type { AddTorrentStickyDto } from './models/AddTorrentStickyDto';
export type { AddUserTorrentDto } from './models/AddUserTorrentDto';
export { AdminCreateNotificationDto } from './models/AdminCreateNotificationDto';
export { AdminCreateTargetedNotificationDto } from './models/AdminCreateTargetedNotificationDto';
export { AdminListFilmsDto } from './models/AdminListFilmsDto';
export { AdminListPendingFilmsDto } from './models/AdminListPendingFilmsDto';
export { AdminListPlaylistsDto } from './models/AdminListPlaylistsDto';
export { AdminListTorrentsDto } from './models/AdminListTorrentsDto';
export { AdvancedPunishmentRecordRuleDto } from './models/AdvancedPunishmentRecordRuleDto';
export { AdvancedRuleDto } from './models/AdvancedRuleDto';
export type { ApplyPunishmentDto } from './models/ApplyPunishmentDto';
export type { AssignPermissionsDto } from './models/AssignPermissionsDto';
export type { AssignRolesDto } from './models/AssignRolesDto';
export type { AutoUploadTorrentDto } from './models/AutoUploadTorrentDto';
export type { AwardIdDto } from './models/AwardIdDto';
export type { BanDaysIdDto } from './models/BanDaysIdDto';
export type { BanReasonIdDto } from './models/BanReasonIdDto';
export type { CheckInfoHashDto } from './models/CheckInfoHashDto';
export type { CreateAwardDto } from './models/CreateAwardDto';
export type { CreateBanDaysDto } from './models/CreateBanDaysDto';
export type { CreateBanReasonDto } from './models/CreateBanReasonDto';
export { CreateCategoryDto } from './models/CreateCategoryDto';
export { CreateFilmDto } from './models/CreateFilmDto';
export type { CreateForumCategoryDto } from './models/CreateForumCategoryDto';
export type { CreateForumPostDto } from './models/CreateForumPostDto';
export type { CreateForumThreadDto } from './models/CreateForumThreadDto';
export { CreatePermissionDto } from './models/CreatePermissionDto';
export type { CreatePromotionDto } from './models/CreatePromotionDto';
export type { CreatePunishmentTypeDto } from './models/CreatePunishmentTypeDto';
export type { CreateRoleDto } from './models/CreateRoleDto';
export type { CreateSeriesDto } from './models/CreateSeriesDto';
export type { CreateSettingDto } from './models/CreateSettingDto';
export type { CreateSimpleTorrentDto } from './models/CreateSimpleTorrentDto';
export type { CreateStickyDto } from './models/CreateStickyDto';
export type { CreateTorrentDto } from './models/CreateTorrentDto';
export type { CreateUnbanReasonDto } from './models/CreateUnbanReasonDto';
export type { DeleteMessageDto } from './models/DeleteMessageDto';
export type { DeleteThankDto } from './models/DeleteThankDto';
export type { DeleteThreadDto } from './models/DeleteThreadDto';
export type { DeleteTorrentDto } from './models/DeleteTorrentDto';
export type { FavoriteMessageDto } from './models/FavoriteMessageDto';
export type { FilmIdDto } from './models/FilmIdDto';
export type { FilmTorrentIdDto } from './models/FilmTorrentIdDto';
export type { ForumCategoryIdDto } from './models/ForumCategoryIdDto';
export type { ForumThreadIdDto } from './models/ForumThreadIdDto';
export type { GetTorrentDto } from './models/GetTorrentDto';
export type { GrantQuotaDto } from './models/GrantQuotaDto';
export type { InviteStatusDto } from './models/InviteStatusDto';
export type { ListAwardsDto } from './models/ListAwardsDto';
export type { ListBanDaysDto } from './models/ListBanDaysDto';
export type { ListBanReasonDto } from './models/ListBanReasonDto';
export type { ListBanRecordsDto } from './models/ListBanRecordsDto';
export type { ListCategoriesDto } from './models/ListCategoriesDto';
export type { ListFavoritesDto } from './models/ListFavoritesDto';
export { ListFilmsDto } from './models/ListFilmsDto';
export type { ListFilmTorrentsDto } from './models/ListFilmTorrentsDto';
export type { ListForumCategoriesDto } from './models/ListForumCategoriesDto';
export type { ListForumPostsDto } from './models/ListForumPostsDto';
export type { ListForumThreadsDto } from './models/ListForumThreadsDto';
export type { ListInboxDto } from './models/ListInboxDto';
export type { ListMessagesDto } from './models/ListMessagesDto';
export type { ListOutboxDto } from './models/ListOutboxDto';
export { ListPendingCoversDto } from './models/ListPendingCoversDto';
export { ListPermissionsDto } from './models/ListPermissionsDto';
export type { ListPromotionsDto } from './models/ListPromotionsDto';
export { ListPunishmentRecordsDto } from './models/ListPunishmentRecordsDto';
export type { ListPunishmentTypeDto } from './models/ListPunishmentTypeDto';
export type { ListRolesDto } from './models/ListRolesDto';
export type { ListSeriesDto } from './models/ListSeriesDto';
export type { ListSeriesFilmsDto } from './models/ListSeriesFilmsDto';
export type { ListStickiesDto } from './models/ListStickiesDto';
export type { ListThreadPromotionsDto } from './models/ListThreadPromotionsDto';
export type { ListThreadsDto } from './models/ListThreadsDto';
export type { ListThreadStickiesDto } from './models/ListThreadStickiesDto';
export type { ListTorrentPromotionsDto } from './models/ListTorrentPromotionsDto';
export type { ListTorrentsDto } from './models/ListTorrentsDto';
export type { ListTorrentStickiesDto } from './models/ListTorrentStickiesDto';
export type { ListTorrentThanksDto } from './models/ListTorrentThanksDto';
export type { ListTorrentUsersDto } from './models/ListTorrentUsersDto';
export type { ListUnbanReasonDto } from './models/ListUnbanReasonDto';
export { ListUsersDto } from './models/ListUsersDto';
export type { ListUserThanksDto } from './models/ListUserThanksDto';
export type { ListUserTorrentsDto } from './models/ListUserTorrentsDto';
export type { LoginDto } from './models/LoginDto';
export type { LoginResultDto } from './models/LoginResultDto';
export type { MarkReadDto } from './models/MarkReadDto';
export { PermissionDto } from './models/PermissionDto';
export type { PermissionIdDto } from './models/PermissionIdDto';
export type { PollDto } from './models/PollDto';
export type { PromotionIdDto } from './models/PromotionIdDto';
export type { PunishmentTypeIdDto } from './models/PunishmentTypeIdDto';
export type { QueryUserPunishmentsDto } from './models/QueryUserPunishmentsDto';
export type { QuickRegisterDto } from './models/QuickRegisterDto';
export type { RecordDownloadDto } from './models/RecordDownloadDto';
export type { RegisterDto } from './models/RegisterDto';
export type { RegisterResultDto } from './models/RegisterResultDto';
export type { RegistrationStatusDto } from './models/RegistrationStatusDto';
export type { RemoveUserTorrentDto } from './models/RemoveUserTorrentDto';
export { ReplyMessageDto } from './models/ReplyMessageDto';
export type { ReportUserTorrentDto } from './models/ReportUserTorrentDto';
export type { RequestEmailCodeDto } from './models/RequestEmailCodeDto';
export type { RequestPasswordResetDto } from './models/RequestPasswordResetDto';
export type { ResetOkDto } from './models/ResetOkDto';
export type { ResetPasswordDto } from './models/ResetPasswordDto';
export { ReviewDto } from './models/ReviewDto';
export type { RevokePunishmentDto } from './models/RevokePunishmentDto';
export type { RoleDto } from './models/RoleDto';
export type { RoleIdDto } from './models/RoleIdDto';
export type { SendInviteDto } from './models/SendInviteDto';
export { SendMessageDto } from './models/SendMessageDto';
export type { SendReportDto } from './models/SendReportDto';
export type { SentDto } from './models/SentDto';
export type { SeriesFilmIdDto } from './models/SeriesFilmIdDto';
export type { SeriesIdDto } from './models/SeriesIdDto';
export type { SetRolePermissionsDto } from './models/SetRolePermissionsDto';
export type { SetUserCategoriesDto } from './models/SetUserCategoriesDto';
export type { StickyIdDto } from './models/StickyIdDto';
export type { ThreadPromotionIdDto } from './models/ThreadPromotionIdDto';
export type { ThreadStickyIdDto } from './models/ThreadStickyIdDto';
export type { TorrentPromotionIdDto } from './models/TorrentPromotionIdDto';
export type { TorrentStickyIdDto } from './models/TorrentStickyIdDto';
export { TrackerReportDto } from './models/TrackerReportDto';
export type { UnbanReasonIdDto } from './models/UnbanReasonIdDto';
export type { UnifiedResponseDto } from './models/UnifiedResponseDto';
export type { UpdateAwardDto } from './models/UpdateAwardDto';
export type { UpdateBanDaysDto } from './models/UpdateBanDaysDto';
export type { UpdateBanReasonDto } from './models/UpdateBanReasonDto';
export { UpdateCategoryDto } from './models/UpdateCategoryDto';
export { UpdateFilmDto } from './models/UpdateFilmDto';
export type { UpdateFilmTorrentDto } from './models/UpdateFilmTorrentDto';
export type { UpdateForumCategoryDto } from './models/UpdateForumCategoryDto';
export { UpdatePermissionDto } from './models/UpdatePermissionDto';
export type { UpdatePromotionDto } from './models/UpdatePromotionDto';
export type { UpdatePunishmentTypeDto } from './models/UpdatePunishmentTypeDto';
export type { UpdateRoleDto } from './models/UpdateRoleDto';
export type { UpdateSeriesDto } from './models/UpdateSeriesDto';
export type { UpdateSeriesFilmDto } from './models/UpdateSeriesFilmDto';
export type { UpdateSettingsItemDto } from './models/UpdateSettingsItemDto';
export type { UpdateSettingsItemsDto } from './models/UpdateSettingsItemsDto';
export type { UpdateStickyDto } from './models/UpdateStickyDto';
export type { UpdateThreadPromotionDto } from './models/UpdateThreadPromotionDto';
export type { UpdateThreadStickyDto } from './models/UpdateThreadStickyDto';
export type { UpdateTorrentDto } from './models/UpdateTorrentDto';
export type { UpdateTorrentPromotionDto } from './models/UpdateTorrentPromotionDto';
export type { UpdateTorrentStickyDto } from './models/UpdateTorrentStickyDto';
export type { UpdateUnbanReasonDto } from './models/UpdateUnbanReasonDto';
export type { UpdateUserBodyDto } from './models/UpdateUserBodyDto';
export { UserDto } from './models/UserDto';
export type { UserIdDto } from './models/UserIdDto';
export { UserListTorrentsDto } from './models/UserListTorrentsDto';
export type { VerifyEmailCodeDto } from './models/VerifyEmailCodeDto';

export { AuditService } from './services/AuditService';
export { AuthService } from './services/AuthService';
export { AwardsService } from './services/AwardsService';
export { BanDaysService } from './services/BanDaysService';
export { BanReasonsService } from './services/BanReasonsService';
export { CategoriesService } from './services/CategoriesService';
export { DevService } from './services/DevService';
export { DictionaryService } from './services/DictionaryService';
export { FilmsService } from './services/FilmsService';
export { ForumCategoriesService } from './services/ForumCategoriesService';
export { ForumPostsService } from './services/ForumPostsService';
export { ForumPromotionsService } from './services/ForumPromotionsService';
export { ForumStickiesService } from './services/ForumStickiesService';
export { ForumThreadsService } from './services/ForumThreadsService';
export { ImagesService } from './services/ImagesService';
export { InvitesService } from './services/InvitesService';
export { MailService } from './services/MailService';
export { MessagesService } from './services/MessagesService';
export { MessagesAdminService } from './services/MessagesAdminService';
export { PasskeyService } from './services/PasskeyService';
export { PermissionsService } from './services/PermissionsService';
export { PlaylistsService } from './services/PlaylistsService';
export { PromotionsService } from './services/PromotionsService';
export { PtGenService } from './services/PtGenService';
export { PunishmentsService } from './services/PunishmentsService';
export { PunishmentTypesService } from './services/PunishmentTypesService';
export { RolesService } from './services/RolesService';
export { SeriesService } from './services/SeriesService';
export { SettingsService } from './services/SettingsService';
export { StickiesService } from './services/StickiesService';
export { ThanksService } from './services/ThanksService';
export { TorrentsService } from './services/TorrentsService';
export { TorrentsTrackerService } from './services/TorrentsTrackerService';
export { UnbanReasonsService } from './services/UnbanReasonsService';
export { UsersService } from './services/UsersService';
