// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiTorrentsByIdData, GetApiTorrentsByIdResponses, GetApiTorrentsData, GetApiTorrentsResponses, PostApiAuthLoginData, PostApiAuthLoginResponses, PostApiAuthRegisterData, PostApiAuthRegisterResponses, PostApiAuthSendVerificationCodeData, PostApiAuthSendVerificationCodeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 用户登录
 */
export const postApiAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthLoginData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiAuthLoginResponses, unknown, ThrowOnError>({
        url: '/api/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 用户注册
 */
export const postApiAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthRegisterData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiAuthRegisterResponses, unknown, ThrowOnError>({
        url: '/api/auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 发送邮箱验证码
 */
export const postApiAuthSendVerificationCode = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthSendVerificationCodeData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiAuthSendVerificationCodeResponses, unknown, ThrowOnError>({
        url: '/api/auth/send-verification-code',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 获取种子列表
 */
export const getApiTorrents = <ThrowOnError extends boolean = false>(options?: Options<GetApiTorrentsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiTorrentsResponses, unknown, ThrowOnError>({
        url: '/api/torrents',
        ...options
    });
};

/**
 * 获取种子详情
 */
export const getApiTorrentsById = <ThrowOnError extends boolean = false>(options: Options<GetApiTorrentsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiTorrentsByIdResponses, unknown, ThrowOnError>({
        url: '/api/torrents/{id}',
        ...options
    });
};
