// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8890' | (string & {});
};

export type Torrent = {
    id?: number;
    title?: string;
    category?: string;
    size?: string;
    seeders?: number;
    leechers?: number;
    rating?: number;
    uploadDate?: string;
    thumbnail?: string;
};

export type PostApiAuthLoginData = {
    body: {
        /**
         * 用户名
         */
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * 登录成功
     */
    200: {
        token?: string;
        user?: {
            id?: number;
            email?: string;
            username?: string;
        };
    };
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthRegisterData = {
    body: {
        email: string;
        username: string;
        password: string;
        /**
         * 邮箱验证码
         */
        verificationCode: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostApiAuthRegisterResponses = {
    /**
     * 注册成功
     */
    200: {
        token?: string;
        user?: {
            id?: number;
            email?: string;
            username?: string;
        };
    };
};

export type PostApiAuthRegisterResponse = PostApiAuthRegisterResponses[keyof PostApiAuthRegisterResponses];

export type PostApiAuthSendVerificationCodeData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/send-verification-code';
};

export type PostApiAuthSendVerificationCodeResponses = {
    /**
     * 验证码发送成功
     */
    200: {
        message?: string;
        /**
         * 验证码过期时间（秒）
         */
        expiry?: number;
    };
};

export type PostApiAuthSendVerificationCodeResponse = PostApiAuthSendVerificationCodeResponses[keyof PostApiAuthSendVerificationCodeResponses];

export type GetApiTorrentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 分类筛选
         */
        category?: string;
        /**
         * 页码
         */
        page?: number;
        /**
         * 每页数量
         */
        limit?: number;
    };
    url: '/api/torrents';
};

export type GetApiTorrentsResponses = {
    /**
     * 种子列表
     */
    200: {
        data?: Array<{
            id?: number;
            title?: string;
            category?: string;
            size?: string;
            seeders?: number;
            leechers?: number;
            rating?: number;
            uploadDate?: string;
        }>;
        total?: number;
        page?: number;
    };
};

export type GetApiTorrentsResponse = GetApiTorrentsResponses[keyof GetApiTorrentsResponses];

export type GetApiTorrentsByIdData = {
    body?: never;
    path: {
        /**
         * 种子ID
         */
        id: number;
    };
    query?: never;
    url: '/api/torrents/{id}';
};

export type GetApiTorrentsByIdResponses = {
    /**
     * 种子详情
     */
    200: {
        id?: number;
        title?: string;
        description?: string;
        category?: string;
        size?: string;
        seeders?: number;
        leechers?: number;
        rating?: number;
        uploadDate?: string;
        magnetLink?: string;
        thumbnail?: string;
    };
};

export type GetApiTorrentsByIdResponse = GetApiTorrentsByIdResponses[keyof GetApiTorrentsByIdResponses];
