export const SECTION_NAME_MAP: Record<string, string> = {
  "/": "首页",
  "/system": "系统设置",
  "/recommendation-config": "推荐配置",

  "/categories/torrent": "种子分类",
  "/categories/movie": "电影分类",
  "/categories/series": "剧集分类",
  "/categories/playlist": "片单分类",
  "/categories/adult/torrent": "成人分类 - 种子",
  "/categories/adult/movie": "成人分类 - 电影",
  "/categories/adult/series": "成人分类 - 剧集",
  "/categories/adult/playlist": "成人分类 - 列表",
  "/torrents": "种子列表",
  "/torrents/records": "种子记录",
  "/torrents/user-records": "用户记录",
  "/movies": "电影管理",
  "/playlists": "片单管理",
  "/store/items": "商品管理",
  "/store/orders": "订单列表",
  "/bonus/adjust": "人工调账",
  "/users": "用户管理",
  "/users/roles": "角色管理",
  "/users/levels": "级别管理",
  "/users/permissions": "权限管理",
  "/dictionary/punishment-types": "处罚类型管理",
  "/dictionary/ban-reasons": "处罚原因管理",
  "/dictionary/unban-reasons": "解除处罚管理",
  "/dictionary/ban-days": "处罚时长管理",
  "/invites/list": "邀请记录",
  "/invites/quota": "邀请名额",
  "/invites/statistics": "邀请统计",
  "/invites/send": "发送邀请",
  "/tickets": "工单管理",
};
