import type { StaffMember } from './types';

export const staffMembers: StaffMember[] = [
  {
    id: '1',
    username: 'SiteAdmin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
    role: 'owner',
    title: '站长',
    joinDate: '2020-01-01',
    responsibilities: ['全站管理', '战略规划', '重大决策', '服务器维护'],
    stats: {
      handledTickets: 2847,
      bannedUsers: 156,
      solvedIssues: 1234,
    },
    status: 'online',
    bio: '负责站点的整体运营和发展方向，确保站点稳定运行。',
    contactAllowed: true,
  },
  {
    id: '2',
    username: 'TechLead',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    role: 'admin',
    title: '技术管理',
    joinDate: '2020-03-15',
    responsibilities: ['技术开发', '系统维护', 'Bug修复', '功能更新'],
    stats: {
      solvedIssues: 3456,
      handledTickets: 1892,
    },
    status: 'online',
    bio: '负责站点技术架构和系统优化，处理各类技术问题。',
    contactAllowed: true,
  },
  {
    id: '3',
    username: 'ContentMaster',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    role: 'admin',
    title: '内容管理',
    joinDate: '2020-05-20',
    responsibilities: ['内容审核', '质量控制', '分类管理', '规则制定'],
    stats: {
      approvedUploads: 5678,
      bannedUsers: 89,
    },
    status: 'away',
    bio: '负责审核上传内容，确保资源质量和分类准确性。',
    contactAllowed: true,
  },
  {
    id: '4',
    username: 'ForumGuardian',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    role: 'moderator',
    title: '论坛版主',
    joinDate: '2021-02-10',
    responsibilities: ['论坛管理', '社区维护', '用户纠纷处理', '活动组织'],
    stats: {
      handledTickets: 1234,
      solvedIssues: 892,
    },
    status: 'online',
    bio: '维护论坛秩序，处理用户投诉和纠纷。',
    contactAllowed: true,
  },
  {
    id: '5',
    username: 'MovieExpert',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    role: 'moderator',
    title: '电影区版主',
    joinDate: '2021-04-22',
    responsibilities: ['电影区管理', '资源审核', '推荐优质内容', '解答疑问'],
    stats: {
      approvedUploads: 2345,
      handledTickets: 567,
    },
    status: 'online',
    bio: '专注于电影区的内容质量和用户体验。',
    contactAllowed: true,
  },
  {
    id: '6',
    username: 'SeriesKing',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
    role: 'moderator',
    title: '剧集区版主',
    joinDate: '2021-06-15',
    responsibilities: ['剧集区管理', '更新追踪', '资源整理', '用户服务'],
    stats: {
      approvedUploads: 1987,
      handledTickets: 432,
    },
    status: 'offline',
    bio: '负责剧集资源的更新和整理，提供优质观剧体验。',
    contactAllowed: true,
  },
  {
    id: '7',
    username: 'UploadPro',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200',
    role: 'uploader',
    title: '优秀上传者',
    joinDate: '2021-08-30',
    responsibilities: ['资源制作', '高质量上传', '技术指导', '新人培训'],
    stats: {
      approvedUploads: 4567,
    },
    status: 'online',
    bio: '专注于制作和上传高质量资源，分享技术经验。',
    contactAllowed: true,
  },
  {
    id: '8',
    username: 'UploadMaster',
    avatar: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=200',
    role: 'uploader',
    title: '资深上传者',
    joinDate: '2021-10-12',
    responsibilities: ['4K资源制作', '音轨处理', '字幕制作', '质量把关'],
    stats: {
      approvedUploads: 3892,
    },
    status: 'away',
    bio: '擅长4K资源制作和音轨处理，追求极致画质。',
    contactAllowed: true,
  },
  {
    id: '9',
    username: 'HelpDesk',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    role: 'support',
    title: '客服专员',
    joinDate: '2022-01-20',
    responsibilities: ['用户咨询', '问题解答', '新手引导', '工单处理'],
    stats: {
      handledTickets: 5678,
      solvedIssues: 4321,
    },
    status: 'online',
    bio: '解答用户疑问，提供技术支持和帮助。',
    contactAllowed: true,
  },
  {
    id: '10',
    username: 'SupportGuru',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200',
    role: 'support',
    title: '技术支持',
    joinDate: '2022-03-08',
    responsibilities: ['技术问题', '账号问题', '下载指导', 'FAQ维护'],
    stats: {
      handledTickets: 4234,
      solvedIssues: 3567,
    },
    status: 'online',
    bio: '专注于解决用户技术问题，优化使用体验。',
    contactAllowed: true,
  },
];

